ARTICLE_TYPE_GROUPS = {
    "Shirts": ["Shirts", "Formal Shirts", "Casual Shirts"],
    "Tshirts": ["Tshirts", "Round Neck Tshirts", "Polo Tshirts", "V-Neck Tshirts", "Lounge Tshirts"],
    "Tops": ["Tops", "Crop Tops", "Tank Tops", "Tube Tops", "Camisoles", "Tunics"],
    "Sweatshirts": ["Sweatshirts", "Hoodies", "Tracksuits"],
    "Sweaters": ["Sweaters"],
    "Kurtas": ["Kurtas", "Kurta Sets"],
    "Kurtis": ["Kurtis"],
    "Jeans": ["Jeans", "Skinny Jeans", "Ripped Jeans", "Bootcut Jeans", "Jeggings"],
    "Trousers": ["Trousers", "Formal Trousers", "Chinos", "Track Pants", "Capris", "Rain Trousers"],
    "Shorts": ["Shorts", "Denim Shorts", "Cargo Shorts", "Lounge Shorts"],
    "Leggings": ["Leggings", "Tights", "Jeggings"],
    "Skirts": ["Skirts", "A-Line Skirts", "Pencil Skirts", "Maxi Skirts"],
    "Dresses": ["Dresses", "Maxi Dresses", "Bodycon Dresses", "A-Line Dresses", "Shift Dresses"],
    "Suits": ["Suits", "Pant Suits", "Skirt Suits", "Nehru Jackets"],
    "Blazers": ["Blazers", "Formal Blazers", "Casual Blazers"],
    "Jackets": ["Jackets", "Denim Jackets", "Leather Jackets", "Bomber Jackets", "Puffer Jackets", "Rain Jacket"],
    "Formal Shoes": ["Formal Shoes", "Oxfords", "Derbys", "Loafers", "Monk Straps", "Booties"],
    "Casual Shoes": ["Casual Shoes", "Sneakers", "Canvas Shoes", "Slip-ons", "Sports Sandals"],
    "Sports Shoes": ["Sports Shoes", "Basketballs", "Footballs"],
    "Heels": ["Heels", "Stilettos", "Pumps", "Wedges", "Kitten Heels"],
    "Flats": ["Flats", "Ballerinas", "Loafers"],
    "Sandals": ["Sandals", "Sports Sandals", "Flip Flops"],
    "Sarees": ["Sarees"],
    "Salwar": ["Salwar", "Churidar", "Patiala", "Salwar and Dupatta"],
    "Belts": ["Belts", "Leather Belts", "Fabric Belts", "Suspenders"],
    "Ties": ["Ties", "Bow Ties", "Ties and Cufflinks"],
    "Watches": ["Watches"],
    "Sunglasses": ["Sunglasses"],
    "Eyewear": ["Eyewear"],
    "Bags": ["Handbags", "Clutches", "Backpacks", "Tote Bags", "Sling Bags", "Wallets", "Laptop Bag", "Duffel Bag", "Messenger Bag", "Trolley Bag", "Mobile Pouch", "Waist Pouch", "Rucksacks"],
    "Jewellery": ["Jewellery Set", "Necklace and Chains", "Pendant", "Earrings", "Ring", "Bracelet", "Bangle", "Headband"],
    "Scarves": ["Scarves", "Stoles"],
    "Hats": ["Caps", "Hats", "Beanies"],
    "Socks": ["Socks", "Stockings"],
    "Gloves": ["Gloves"],
    "Mufflers": ["Mufflers"],
    "Innerwear": ["Bra", "Briefs", "Innerwear Vests", "Boxers", "Trunk", "Robe", "Bath Robe"],
    "Loungewear and Nightwear": ["Night suits", "Lounge Pants", "Baby Dolls", "Nightdress", "Lounge Tshirts", "Lounge Shorts"],
    "Swimwear": ["Swimwear"],
    "Shapewear": ["Shapewear"],
    "Accessories": ["Accessories", "Accessory Gift Set", "Travel Accessory"],
    "Dupatta": ["Dupatta"],
    "Shrug": ["Shrug"],
    "Waistcoat": ["Waistcoat"],
    "Jumpsuits and Rompers": ["Jumpsuit", "Rompers"],  # Grouped similar one-piece garments
    "Lehenga Choli": ["Lehenga Choli"],
    "Clothing Set": ["Clothing Set"],
    "Blouse": ["Blouse"],
    "Cufflinks": ["Cufflinks"],
    "Shoe Accessories": ["Shoe Accessories", "Shoe Laces"],
    "Wristbands": ["Wristbands"],
    "Free Gifts": ["Free Gifts"],
    "Water Bottle": ["Water Bottle"],
    "Fragrance": ["Deodorant", "Perfume and Body Mist", "Fragrance Gift Set"],
    "Makeup": ["Lipstick", "Lip Gloss", "Lip Care", "Lip Liner", "Lip Plumper", "Foundation and Primer", "Highlighter and Blush", "Compact", "Kajal and Eyeliner", "Eyeshadow", "Mascara", "Concealer", "Makeup Remover"],
    "Nails": ["Nail Polish", "Nail Essentials"],
    "Skincare": ["Face Wash and Cleanser", "Face Moisturisers", "Eye Cream", "Face Scrub and Exfoliator", "Mask and Peel", "Face Serum and Gel", "Toner", "Sunscreen"],
    "Bath and Body": ["Body Lotion", "Body Wash and Scrub"],
    "Haircare": ["Hair Colour", "Hair Accessory"],
    "Mens Grooming": ["Mens Grooming Kit"],
    "Keychain": ["Key chain"],
    "Tech Accessories": ["Ipad", "Tablet Sleeve"],
    "Umbrellas": ["Umbrellas"],
    "Home Decor": ["Cushion Covers"]
}

COMPATIBLE_TYPES = {
    "Shirts": ["Trousers", "Jeans", "Shorts", "Blazers", "Waistcoat", "Formal Shoes", "Belts", "Ties", "Watches", "Cufflinks", "Nehru Jackets", "Suits", "Chinos"],
    "Formal Shirts": ["Trousers", "Formal Shoes", "Belts", "Ties", "Watches", "Cufflinks", "Suits", "Blazers", "Nehru Jackets"],
    "Casual Shirts": ["Jeans", "Shorts", "Chinos", "Casual Shoes", "Sneakers", "Belts", "Sunglasses", "Caps"],
    "Tshirts": ["Jeans", "Shorts", "Track Pants", "Jackets", "Casual Shoes", "Caps", "Sunglasses", "Backpacks", "Sweatshirts", "Lounge Pants", "Sports Shoes", "Flip Flops", "Skirts"],
    "Round Neck Tshirts": ["Jeans", "Shorts", "Track Pants", "Casual Shoes", "Sneakers", "Caps"],
    "Polo Tshirts": ["Jeans", "Shorts", "Chinos", "Casual Shoes", "Loafers", "Belts"],
    "V-Neck Tshirts": ["Jeans", "Shorts", "Casual Shoes", "Sneakers"],
    "Lounge Tshirts": ["Lounge Pants", "Lounge Shorts", "Flip Flops", "Slippers"],
    "Tops": ["Jeans", "Skirts", "Shorts", "Jackets", "Leggings", "Heels", "Flats", "Sandals", "Bags", "Trousers", "Scarves", "Blazers", "Jeggings"],
    "Crop Tops": ["Jeans", "Skirts", "Shorts", "Heels", "Sandals", "Jackets"],
    "Tank Tops": ["Jeans", "Shorts", "Skirts", "Casual Shoes", "Sneakers", "Sandals"],
    "Tube Tops": ["Jeans", "Skirts", "Shorts", "Heels", "Sandals", "Jackets"],
    "Camisoles": ["Jeans", "Skirts", "Shorts", "Blazers", "Cardigans"],
    "Tunics": ["Leggings", "Jeans", "Trousers", "Flats", "Sandals"],
    "Sweatshirts": ["Jeans", "Track Pants", "Caps", "Sports Shoes", "Casual Shoes", "Shorts", "Lounge Pants"],
    "Hoodies": ["Jeans", "Track Pants", "Casual Shoes", "Sneakers", "Shorts"],
    "Tracksuits": ["Sports Shoes", "Sneakers", "Caps"],
    "Sweaters": ["Jeans", "Trousers", "Skirts", "Leggings", "Boots", "Formal Shoes", "Casual Shoes", "Scarves", "Hats", "Chinos"],
    "Kurtas": ["Churidar", "Trousers", "Leggings", "Dupatta", "Sandals", "Flats", "Jewellery", "Salwar", "Patiala", "Juttis", "Mojaris"],
    "Kurta Sets": ["Sandals", "Flats", "Jewellery", "Dupatta", "Juttis", "Mojaris"],
    "Kurtis": ["Churidar", "Leggings", "Jeans", "Dupatta", "Sandals", "Flats", "Jewellery", "Salwar", "Patiala", "Skirts", "Juttis", "Mojaris"],
    "Jeans": ["Shirts", "Tshirts", "Tops", "Casual Shoes", "Belts", "Jackets", "Sweatshirts", "Heels", "Boots", "Sandals", "Sneakers", "Sweaters"],
    "Skinny Jeans": ["Tops", "Shirts", "Tshirts", "Heels", "Boots", "Flats", "Sneakers"],
    "Ripped Jeans": ["Tshirts", "Casual Shirts", "Tops", "Sneakers", "Boots", "Casual Shoes"],
    "Bootcut Jeans": ["Boots", "Heels", "Tops", "Shirts", "Tshirts"],
    "Jeggings": ["Tops", "Tshirts", "Shirts", "Kurtis", "Tunics", "Casual Shoes", "Boots", "Heels", "Flats"],
    "Trousers": ["Shirts", "Tshirts", "Blazers", "Formal Shoes", "Belts", "Ties", "Watches", "Sweaters", "Jackets", "Casual Shoes", "Socks", "Cufflinks", "Suits", "Nehru Jackets"],
    "Formal Trousers": ["Formal Shirts", "Formal Shoes", "Belts", "Ties", "Blazers", "Suits"],
    "Chinos": ["Shirts", "Tshirts", "Polo Tshirts", "Casual Shoes", "Loafers", "Belts"],
    "Track Pants": ["Tshirts", "Sweatshirts", "Sports Shoes", "Casual Shoes", "Jackets"],
    "Capris": ["Tops", "Tshirts", "Casual Shoes", "Sandals", "Flats"],
    "Rain Trousers": ["Rain Jacket", "Boots"],
    "Shorts": ["Tshirts", "Shirts", "Casual Shoes", "Sandals", "Sunglasses", "Caps", "Flip Flops", "Sports Shoes", "Tank Tops"],
    "Denim Shorts": ["Tshirts", "Tops", "Casual Shoes", "Sandals", "Sneakers"],
    "Cargo Shorts": ["Tshirts", "Casual Shirts", "Boots", "Sneakers", "Sandals"],
    "Lounge Shorts": ["Lounge Tshirts", "Tank Tops", "Flip Flops", "Slippers"],
    "Leggings": ["Tunics", "Kurtis", "Long Tshirts", "Flats", "Casual Shoes", "Tops", "Dresses", "Sweaters", "Sports Shoes", "Boots"],
    "Tights": ["Dresses", "Skirts", "Tunics", "Heels", "Boots", "Flats"],
    "Skirts": ["Tops", "Shirts", "Flats", "Heels", "Sandals", "Belts", "Bags", "Tights", "Blouses", "Jackets", "Boots", "Sweaters"],
    "A-Line Skirts": ["Tops", "Shirts", "Blouses", "Heels", "Flats", "Sandals", "Boots"],
    "Pencil Skirts": ["Blouses", "Shirts", "Heels", "Pumps"],
    "Maxi Skirts": ["Tops", "Tank Tops", "Sandals", "Flats"],
    "Dresses": ["Heels", "Flats", "Sandals", "Jackets", "Clutches", "Jewellery", "Belts", "Sunglasses", "Scarves", "Boots", "Hats", "Tights"],
    "Maxi Dresses": ["Sandals", "Flats", "Wedges", "Hats", "Sunglasses"],
    "Bodycon Dresses": ["Heels", "Stilettos", "Clutches", "Jewellery"],
    "A-Line Dresses": ["Heels", "Flats", "Sandals", "Wedges", "Belts"],
    "Shift Dresses": ["Flats", "Sandals", "Heels", "Boots"],
    "Suits": ["Formal Shoes", "Shirts", "Ties", "Belts", "Watches", "Cufflinks", "Pocket Squares"],
    "Pant Suits": ["Formal Shoes", "Shirts", "Ties", "Belts", "Watches", "Cufflinks"],
    "Skirt Suits": ["Formal Shoes", "Blouses", "Heels", "Pumps", "Belts", "Watches"],
    "Nehru Jackets": ["Shirts", "Kurtas", "Trousers", "Formal Shoes", "Mojaris"],
    "Blazers": ["Shirts", "Trousers", "Jeans", "Formal Shoes", "Casual Shoes", "Ties", "Belts", "Dresses", "Skirts", "Tshirts"],
    "Formal Blazers": ["Formal Shirts", "Trousers", "Formal Shoes", "Ties", "Dresses", "Skirts"],
    "Casual Blazers": ["Tshirts", "Jeans", "Chinos", "Casual Shoes", "Sneakers", "Dresses"],
    "Jackets": ["Tshirts", "Shirts", "Jeans", "Trousers", "Casual Shoes", "Sweatshirts", "Dresses", "Skirts", "Tops", "Shorts", "Leggings"],
    "Denim Jackets": ["Tshirts", "Shirts", "Jeans", "Dresses", "Skirts", "Casual Shoes", "Sneakers"],
    "Leather Jackets": ["Tshirts", "Shirts", "Jeans", "Boots", "Casual Shoes", "Dresses"],
    "Bomber Jackets": ["Tshirts", "Jeans", "Casual Shoes", "Sneakers", "Shorts"],
    "Puffer Jackets": ["Sweaters", "Jeans", "Track Pants", "Boots", "Sneakers"],
    "Rain Jacket": ["Rain Trousers", "Boots", "Umbrellas"],
    "Formal Shoes": ["Trousers", "Shirts", "Suits", "Belts", "Socks", "Dresses", "Skirts"],
    "Oxfords": ["Suits", "Formal Trousers", "Shirts", "Ties"],
    "Derbys": ["Suits", "Formal Trousers", "Shirts", "Chinos"],
    "Loafers": ["Chinos", "Trousers", "Jeans", "Shirts"],
    "Monk Straps": ["Suits", "Formal Trousers", "Shirts"],
    "Booties": ["Dresses", "Skirts", "Jeans", "Trousers"],
    "Casual Shoes": ["Jeans", "Tshirts", "Shorts", "Track Pants", "Socks", "Dresses", "Skirts"],
    "Sneakers": ["Jeans", "Shorts", "Track Pants", "Dresses", "Skirts", "Tshirts", "Tops"],
    "Canvas Shoes": ["Jeans", "Shorts", "Dresses", "Skirts", "Tshirts"],
    "Slip-ons": ["Jeans", "Shorts", "Dresses"],
    "Sports Sandals": ["Shorts", "Swimwear"],
    "Sports Shoes": ["Track Pants", "Shorts", "Tshirts", "Socks", "Leggings"],
    "Basketballs": ["Shorts", "Tank Tops", "Socks", "Wristbands"],
    "Footballs": ["Shorts", "Socks", "Shin Guards"],
    "Heels": ["Dresses", "Skirts", "Trousers", "Jeans", "Jumpsuits", "Sarees"],
    "Stilettos": ["Dresses", "Jumpsuits", "Skinny Jeans"],
    "Pumps": ["Dresses", "Skirts", "Trousers"],
    "Wedges": ["Dresses", "Skirts", "Jeans", "Shorts"],
    "Kitten Heels": ["Dresses", "Skirts", "Trousers"],
    "Flats": ["Dresses", "Jeans", "Skirts", "Leggings", "Shorts", "Kurtas", "Kurtis", "Salwar", "Trousers"],
    "Ballerinas": ["Dresses", "Skirts", "Jeans"],
    "Sandals": ["Dresses", "Skirts", "Jeans", "Shorts", "Kurtas", "Salwar", "Kurtis", "Lehenga Choli"],
    "Flip Flops": ["Shorts", "Dresses", "Jeans", "Swimwear"],
    "Sarees": ["Sandals", "Heels", "Jewellery", "Clutches", "Blouse", "Bangles"],
    "Salwar": ["Kurtas", "Kurtis", "Dupatta", "Sandals", "Flats", "Jewellery", "Juttis", "Mojaris"],
    "Churidar": ["Kurtas", "Kurtis"],
    "Patiala": ["Kurtas", "Kurtis", "Juttis"],
    "Salwar and Dupatta": ["Kurtas", "Kurtis", "Sandals", "Flats", "Jewellery"],
    "Belts": ["Trousers", "Jeans", "Dresses", "Skirts", "Shorts", "Suits", "Tunics"],
    "Leather Belts": ["Trousers", "Jeans"],
    "Fabric Belts": ["Dresses", "Skirts", "Tunics"],
    "Suspenders": ["Trousers", "Formal Shirts", "Suits"],
    "Ties": ["Shirts", "Suits", "Blazers"],
    "Bow Ties": ["Shirts", "Suits"],
    "Ties and Cufflinks": ["Formal Shirts", "Suits", "Blazers"],
    "Watches": [],
    "Sunglasses": [],
    "Eyewear": [],
    "Handbags": [],
    "Clutches": ["Dresses", "Sarees", "Lehenga Choli", "Jumpsuits"],
    "Backpacks": [],
    "Tote Bags": [],
    "Sling Bags": [],
    "Wallets": [],
    "Laptop Bag": [],
    "Duffel Bag": [],
    "Messenger Bag": [],
    "Trolley Bag": [],
    "Mobile Pouch": [],
    "Waist Pouch": [],
    "Rucksacks": [],
    "Jewellery Set": ["Sarees", "Lehenga Choli", "Dresses", "Kurtas", "Kurtis", "Salwar"],
    "Necklace and Chains": [],
    "Pendant": [],
    "Earrings": [],
    "Ring": [],
    "Bracelet": [],
    "Bangle": ["Sarees", "Lehenga Choli"],
    "Headband": [],
    "Scarves": ["Dresses", "Tops", "Jackets", "Suits", "Blazers"],
    "Stoles": ["Sarees", "Dresses", "Kurtas"],
    "Caps": ["Tshirts", "Jeans", "Shorts", "Dresses"],
    "Hats": ["Dresses", "Suits", "Sunglasses"],
    "Beanies": ["Sweaters", "Jackets", "Jeans", "Scarves"],
    "Socks": ["Shoes", "Sports Shoes", "Formal Shoes", "Casual Shoes", "Boots"],
    "Stockings": ["Dresses", "Skirts", "Heels", "Boots"],
    "Gloves": ["Jackets", "Suits"],
    "Mufflers": ["Suits", "Jackets"],
    "Bra": ["Tops", "Dresses", "Shirts", "Tshirts"],
    "Briefs": ["Trousers", "Jeans", "Shorts"],
    "Innerwear Vests": ["Shirts", "Tshirts"],
    "Boxers": [],
    "Trunk": ["Trousers", "Jeans", "Shorts"],
    "Robe": [],
    "Bath Robe": [],
    "Night suits": ["Slippers", "Flip Flops"],
    "Lounge Pants": ["Lounge Tshirts", "Tshirts"],
    "Baby Dolls": ["Slippers"],
    "Nightdress": ["Slippers", "Flip Flops"],
    "Lounge Tshirts": ["Lounge Pants", "Lounge Shorts"],
    "Lounge Shorts": ["Lounge Tshirts", "Tank Tops"],
    "Swimwear": ["Flip Flops", "Sandals", "Sunglasses", "Hats"],
    "Shapewear": ["Dresses", "Skirts", "Trousers"],
    "Accessories": [],
    "Accessory Gift Set": [],
    "Travel Accessory": [],
    "Dupatta": ["Kurtas", "Salwar", "Lehenga Choli", "Kurtis"],
    "Shrug": ["Tops", "Dresses", "Jeans", "Tshirts"],
    "Waistcoat": ["Shirts", "Trousers", "Formal Shoes", "Suits", "Nehru Jackets"],
    "Jumpsuit": ["Jackets", "Heels", "Sandals", "Belts", "Bags", "Jewellery", "Clutches", "Sunglasses"],
    "Rompers": ["Sandals", "Casual Shoes", "Sunglasses"],
    "Lehenga Choli": ["Dupatta", "Sandals", "Heels", "Jewellery", "Clutches", "Bangles"],
    "Clothing Set": [],
    "Blouse": ["Sarees", "Lehenga Choli"],
    "Cufflinks": ["Formal Shirts", "Suits", "Blazers"],
    "Shoe Accessories": [],
    "Shoe Laces": ["Shoes"],
    "Wristbands": [],
    "Free Gifts": [],
    "Water Bottle": [],
    "Deodorant": [],
    "Perfume and Body Mist": [],
    "Fragrance Gift Set": [],
    "Lipstick": ["Dresses", "Tops", "Sarees"],
    "Lip Gloss": ["Dresses", "Tops"],
    "Lip Care": [],
    "Lip Liner": [],
    "Lip Plumper": [],
    "Foundation and Primer": [],
    "Highlighter and Blush": [],
    "Compact": [],
    "Kajal and Eyeliner": [],
    "Eyeshadow": [],
    "Mascara": [],
    "Concealer": [],
    "Makeup Remover": [],
    "Nail Polish": [],
    "Nail Essentials": [],
    "Face Wash and Cleanser": [],
    "Face Moisturisers": [],
    "Eye Cream": [],
    "Face Scrub and Exfoliator": [],
    "Mask and Peel": [],
    "Face Serum and Gel": [],
    "Toner": [],
    "Sunscreen": [],
    "Body Lotion": [],
    "Body Wash and Scrub": [],
    "Hair Colour": [],
    "Hair Accessory": [],
    "Mens Grooming Kit": [],
    "Key chain": [],
    "Ipad": [],
    "Tablet Sleeve": [],
    "Umbrellas": ["Rain Jacket", "Rain Trousers"],
    "Cushion Covers": []
}

ACCESSORY_COMBINATIONS = {
    "Formal": ["Belts", "Ties", "Watches", "Cufflinks", "Formal Shoes", "Pocket Squares", "Leather Belts", "Briefcases", "Messenger Bags", "Socks"],
    "Casual": ["Sunglasses", "Caps", "Backpacks", "Casual Shoes", "Sneakers", "Belts", "Watches", "Tote Bags", "Sling Bags", "Hats", "Scarves", "Jewellery", "Key chain"],
    "Sports": ["Caps", "Sports Shoes", "Socks", "Wristbands", "Headbands", "Duffel Bag", "Water Bottle", "Sunglasses"],
    "Party": ["Jewellery", "Clutches", "Heels", "Scarves", "Belts", "Watches", "Hair Accessory"],
    "Ethnic": ["Jewellery", "Bangles", "Sandals", "Mojaris", "Juttis", "Dupatta", "Stoles", "Clutches"],
    "Travel": ["Backpacks", "Tote Bags", "Duffel Bags", "Sunglasses", "Hats", "Scarves", "Sandals", "Wallets", "Trolley Bag", "Waist Pouch", "Rucksacks", "Travel Accessory"],
    "Work": ["Formal Shoes", "Belts", "Ties", "Watches", "Laptop Bag", "Messenger Bags", "Handbags"],
    "Home": ["Bath Robe", "Robe", "Cushion Covers"]
}

SEASONAL_ACCESSORIES = {
    "Winter": ["Scarves", "Gloves", "Mufflers", "Beanies", "Hats", "Boots", "Socks", "Body Lotion"],
    "Summer": ["Sunglasses", "Flip Flops", "Hats", "Sandals", "Caps", "Sunscreen"],
    "Spring": ["Scarves", "Flats", "Ballerinas", "Jackets", "Sandals", "Sunglasses"],
    "Fall": ["Jackets", "Boots", "Scarves", "Sweaters", "Hats", "Beanies", "Gloves"]
}

COLOR_COMPATIBILITY = {
    "Navy Blue": ["White", "Grey", "Beige", "Brown", "Red", "Pink", "Mustard", "Olive", "Tan"],
    "Blue": ["White", "Grey", "Beige", "Yellow", "Orange", "Pink", "Green"],
    "Silver": ["Black", "White", "Grey", "Blue", "Purple", "Pink"],
    "Black": ["White", "Grey", "Red", "Pink", "Blue", "Gold", "Silver"],
    "Grey": ["White", "Black", "Blue", "Pink", "Red", "Purple", "Green"],
    "Green": ["White", "Beige", "Brown", "Navy Blue", "Grey", "Yellow"],
    "Purple": ["White", "Grey", "Silver", "Gold", "Pink"],
    "White": ["Black", "Grey", "Blue", "Red", "Green", "Purple"],
    "Beige": ["Brown", "Blue", "Navy Blue", "White", "Green", "Red", "Black"],
    "Brown": ["Beige", "White", "Green", "Navy Blue", "Tan", "Gold"],
    "Bronze": ["Black", "Brown", "Cream", "Teal", "Burgundy"],
    "Teal": ["White", "Beige", "Brown", "Gold", "Coral"],
    "Copper": ["Black", "White", "Teal", "Green", "Navy Blue"],
    "Pink": ["White", "Grey", "Blue", "Black", "Green"],
    "Off White": ["Brown", "Blue", "Black", "Red", "Green"],
    "Maroon": ["White", "Beige", "Grey", "Gold", "Black", "Navy Blue"],
    "Red": ["White", "Black", "Grey", "Blue", "Navy Blue", "Gold"],
    "Khaki": ["White", "Navy Blue", "Brown", "Black", "Burgundy"],
    "Orange": ["Blue", "White", "Black", "Brown"],
    "Coffee Brown": ["Beige", "Cream", "Tan", "Gold", "Teal"],
    "Yellow": ["Blue", "White", "Grey", "Green", "Purple", "Black"],
    "Charcoal": ["White", "Grey", "Pink", "Red", "Blue"],
    "Gold": ["Black", "White", "Red", "Burgundy", "Navy Blue"],
    "Steel": ["Black", "White", "Grey", "Blue", "Navy Blue"],
    "Tan": ["Brown", "White", "Blue", "Navy Blue", "Green"],
    "Multi": [],
    "Magenta": ["White", "Black", "Grey", "Yellow"],
    "Lavender": ["White", "Grey", "Silver", "Pink", "Blue"],
    "Sea Green": ["White", "Beige", "Coral", "Navy Blue", "Tan"],
    "Cream": ["Brown", "Beige", "Gold", "Navy Blue"],
    "Peach": ["White", "Grey", "Navy Blue", "Green"],
    "Olive": ["White", "Black", "Beige", "Brown"],
    "Skin": ["White", "Black", "Brown", "Beige"],
    "Burgundy": ["White", "Black", "Gold", "Navy Blue"],
    "Grey Melange": ["White", "Black", "Blue", "Red"],
    "Rust": ["White", "Beige", "Navy Blue", "Green"],
    "Rose": ["White", "Grey", "Black", "Gold"],
    "Lime Green": ["White", "Black", "Grey"],
    "Mauve": ["White", "Grey", "Silver", "Pink", "Blue"],
    "Turquoise Blue": ["White", "Beige", "Coral", "Navy Blue", "Tan"],
    "Metallic": ["Black", "White", "Grey", "Blue", "Purple"],
    "Mustard": ["Navy Blue", "White", "Grey", "Black"],
    "Taupe": ["White", "Black", "Beige", "Brown", "Navy Blue"],
    "Nude": ["White", "Black", "Brown", "Beige"],
    "Mushroom Brown": ["White", "Beige", "Brown", "Green"],
    "Fluorescent Green": ["Black", "White", "Grey"]
}
