"""This file contains the data loader for the fashion dataset."""

article_type_groups = {
    "Shirts": ["Shirts", "Formal Shirts", "Casual Shirts"],
    "Tshirts": ["Tshirts", "Round Neck Tshirts", "Polo Tshirts", "V-Neck Tshirts"],
    "Tops": ["Tops", "Crop Tops", "Tank Tops", "Tube Tops"],
    "Sweatshirts": ["Sweatshirts", "Hoodies"],
    "Kurtas": ["Kurtas", "Kurtis"],
    "Jeans": ["Jeans", "Skinny Jeans", "Ripped Jeans", "Bootcut Jeans"],
    "Trousers": ["Trousers", "Formal Trousers", "Chinos"],
    "Shorts": ["Shorts", "Denim Shorts", "Cargo Shorts"],
    "Leggings": ["Leggings", "Jeggings"],
    "Skirts": [
        "Skirts",
        "A-Line Skirts",
        "Pencil Skirts",
        "Maxi Skirts",
    ],
    "Dresses": [
        "Dresses",
        "Maxi Dresses",
        "Bodycon Dresses",
        "A-Line Dresses",
        "Shift Dresses",
    ],
    "Suits": ["Suits", "Pant Suits", "Skirt Suits"],
    "Blazers": ["Blazers", "Formal Blazers", "Casual Blazers"],
    "Jackets": [
        "Jackets",
        "Denim Jackets",
        "Leather Jackets",
        "Bomber Jackets",
        "Puffer Jackets",
    ],
    "Formal Shoes": [
        "Formal Shoes",
        "Oxfords",
        "Derbys",
        "Loafers",
        "Monk Straps",
    ],
    "Casual Shoes": [
        "Casual Shoes",
        "Sneakers",
        "Canvas Shoes",
        "Slip-ons",
    ],
    "Heels": ["Heels", "Stilettos", "Pumps", "Wedges", "Kitten Heels"],
    "Flats": ["Flats", "Ballerinas", "Loafers"],
    "Sarees": ["Sarees"],
    "Salwar": ["Salwar", "Churidar", "Patiala"],
    "Belts": ["Belts", "Leather Belts", "Fabric Belts"],
    "Ties": ["Ties", "Bow Ties"],
    "Watches": ["Watches"],
    "Sunglasses": ["Sunglasses"],
    "Bags": [
        "Handbags",
        "Clutches",
        "Backpacks",
        "Tote Bags",
        "Sling Bags",
        "Wallets",
        "Laptop Bag",
        "Duffel Bag",
        "Messenger Bag",
    ],
    "Jewellery": [
        "Jewellery Set",
        "Necklace and Chains",
        "Pendant",
        "Earrings",
        "Ring",
        "Bracelet",
        "Bangle",
    ],
    "Scarves": ["Scarves", "Stoles"],
    "Hats": ["Caps", "Hats"],
    "Socks": ["Socks"],
    "Gloves": ["Gloves"],
    "Mufflers": ["Mufflers"],
}
